defmodule StompexTest do
  use ExUnit.Case
  doctest Stompex
  alias Stompex.FrameHandler
  alias Stompex.Frame

  test "can process a simple message" do
    result = FrameHandler.parse_frames(simple_data, nil)
    assert Enum.at(result, 0) == %Frame{
      cmd: "MESSAGE",
      headers: %{
        "destination" => "/topic/TRAIN_MVT_ALL_TOC",
        "expires" => "1476385896127",
        "message-id" => "ID\\cec2netrailwmq1-44888-1476172009944-1\\c1\\c2\\c22\\c20885",
        "persistent" => "true",
        "priority" => "4",
        "subscription" => "0",
        "timestamp" => "1476385596127",
        "transformation" => "jms-xml"
      },
      content_type: nil,
      body: "[{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476385592000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476389220000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476389220000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"78400\",\"actual_timestamp\":\"1476389220000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 1\",\"division_code\":\"71\",\"train_terminated\":\"false\",\"train_id\":\"782P94MY13\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"25441000\",\"toc_id\":\"71\",\"loc_stanox\":\"78400\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"78410\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476385593000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476388830000\",\"timetable_variation\":\"7\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"83038\",\"actual_timestamp\":\"1476389220000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"25\",\"train_terminated\":\"false\",\"train_id\":\"731C92MW13\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"25397003\",\"toc_id\":\"25\",\"loc_stanox\":\"83038\",\"auto_expected\":\"true\",\"direction_ind\":\"\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"83109\",\"line_ind\":\"\"}}]",
      complete: true
    }
  end

  test "can process a message that includes a null line" do
    result = FrameHandler.parse_frames(null_line_data, nil)
    assert Enum.at(result, 0) == %Frame{
      cmd: "MESSAGE",
      headers: %{
        "destination" => "/topic/TRAIN_MVT_ALL_TOC",
        "expires" => "1476704991451",
        "message-id" => "ID\\cec2netrailwmq1-52825-1476640390449-1\\c29\\c2\\c1\\c4529",
        "persistent" => "true",
        "priority" => "4",
        "subscription" => "0",
        "timestamp" => "1476704691451",
        "transformation" => "jms-xml"
      },
      content_type: nil,
      body: "[{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476385592000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476389220000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476389220000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"78400\",\"actual_timestamp\":\"1476389220000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 1\",\"division_code\":\"71\",\"train_terminated\":\"false\",\"train_id\":\"782P94MY13\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"25441000\",\"toc_id\":\"71\",\"loc_stanox\":\"78400\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"78410\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476385593000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476388830000\",\"timetable_variation\":\"7\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"83038\",\"actual_timestamp\":\"1476389220000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"25\",\"train_terminated\":\"false\",\"train_id\":\"731C92MW13\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"25397003\",\"toc_id\":\"25\",\"loc_stanox\":\"83038\",\"auto_expected\":\"true\",\"direction_ind\":\"\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"83109\",\"line_ind\":\"\"}}]",
      complete: true
    }
  end

  defp simple_data do
    stomp_frame = """
    MESSAGE
    message-id:ID\\cec2netrailwmq1-44888-1476172009944-1\\c1\\c2\\c22\\c20885
    transformation:jms-xml
    destination:/topic/TRAIN_MVT_ALL_TOC
    timestamp:1476385596127
    expires:1476385896127
    subscription:0
    persistent:true
    priority:4

    [{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476385592000\",\"source_system_id\":\"TRUST\"},
    \"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476389220000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476389220000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"78400\",\"actual_timestamp\":\"1476389220000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 1\",\"division_code\":\"71\",\"train_terminated\":\"false\",\"train_id\":\"782P94MY13\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"25441000\",\"toc_id\":\"71\",\"loc_stanox\":\"78400\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"78410\",\"line_ind\":\"\"}},
    {\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476385593000\",\"source_system_id\":\"TRUST\"},
    \"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476388830000\",\"timetable_variation\":\"7\",\"origi
    nal_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"83038\",\"actual_timestamp\":\"1476389220000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"25\",\"train_terminated\":\"false\",\"train_id\":\"731C92MW13\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"25397003\",\"toc_id\":\"25\",\"loc_stanox\":\"83038\",\"auto_expected\":\"true\",\"direction_ind\":\"\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"83109\",\"line_ind\":\"\"}}]
    """ <> <<0>> <> "\n"
  end

  defp null_line_data do
    stomp_frame = """
    MESSAGE
    message-id:ID\\cec2netrailwmq1-52825-1476640390449-1\\c29\\c2\\c1\\c4529
    transformation:jms-xml
    destination:/topic/TRAIN_MVT_ALL_TOC
    timestamp:1476704691451
    expires:1476704991451
    subscription:0
    persistent:true
    priority:4

    [{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704686000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476707970000\",\"timetable_variation\":\"5\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"5\",\"reporting_stanox\":\"87959\",\"actual_timestamp\":\"1476708240000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"88\",\"train_terminated\":\"false\",\"train_id\":\"875E85MJ17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"24788005\",\"toc_id\":\"88\",\"loc_stanox\":\"87959\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"2\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"86471\",\"line_ind\":\"L\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"SV2W\",\"user_id\":\"#PEE0031\",\"original_data_source\":\"SDR\",\"msg_queue_timestamp\":\"1476704686000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476706920000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476706920000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"36169\",\"actual_timestamp\":\"1476706920000\",\"correction_ind\":\"false\",\"event_source\":\"MANUAL\",\"train_file_address\":\"00V\",\"plat
    form\":\"\",\"division_code\":\"54\",\"train_terminated\":\"false\",\"train_id\":\"366E10CC17\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"56461882\",\"toc_id\":\"54\",\"loc_stanox\":\"36169\",\"auto_expected\":\"false\",\"direction_ind\":\"\",\"route\":\"\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"36600\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704686000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476706980000\",\"timetable_variation\":\"21\",\"original_loc_timestamp\":\"\",\"current_train_id\":null,\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"3\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708240000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":\"PFN\",\"platform\":\"\",\"division_code\":\"00\",\"train_terminated\":\"false\",\"train_id\":\"45614X1G17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"53694102\",\"toc_id\":\"00\",\"loc_stanox\":\"22002\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"1\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"21425\",\"line_ind\":\"S\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704688000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_ty
    pe\":\"DEPARTURE\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708210000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"7\",\"reporting_stanox\":\"87903\",\"actual_timestamp\":\"1476708240000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"25\",\"train_terminated\":\"false\",\"train_id\":\"741O70MJ17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"25521007\",\"toc_id\":\"25\",\"loc_stanox\":\"87903\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"1\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"87911\",\"line_ind\":\"S\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704688000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476707280000\",\"timetable_variation\":\"18\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708360000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"88\",\"train_terminated\":\"false\",\"train_id\":\"871R10MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"24745000\",\"to
    c_id\":\"88\",\"loc_stanox\":\"87704\",\"auto_expected\":\"true\",\"direction_ind\":\"\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"87801\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704688000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476708240000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708270000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"6\",\"reporting_stanox\":\"87685\",\"actual_timestamp\":\"1476708240000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"88\",\"train_terminated\":\"false\",\"train_id\":\"872E42MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"24785000\",\"toc_id\":\"88\",\"loc_stanox\":\"87685\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"1\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"87687\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"LYJ8\",\"user_id\":\"#QHPA012\",\"original_data_source\":\"TRUST DA\",\"msg_queue_timestamp\":\"1476704688000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476706080000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476706080000\",\"timetable_variation\":\"30\",\"original_loc_timestamp\":\"\",\"current_t
    rain_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"3\",\"reporting_stanox\":\"47221\",\"actual_timestamp\":\"1476707880000\",\"correction_ind\":\"false\",\"event_source\":\"MANUAL\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"88\",\"train_terminated\":\"false\",\"train_id\":\"475C18MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"21788001\",\"toc_id\":\"88\",\"loc_stanox\":\"47221\",\"auto_expected\":\"true\",\"direction_ind\":\"\",\"route\":\"\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"47215\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704688000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708300000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708300000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"30\",\"train_terminated\":\"false\",\"train_id\":\"889F27ML17\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"22218000\",\"toc_id\":\"30\",\"loc_stanox\":\"52082\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"52080\",\"line_i
    nd\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704688000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476708240000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708240000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"2\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708240000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"30\",\"train_terminated\":\"false\",\"train_id\":\"529C30ML17\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"22215003\",\"toc_id\":\"30\",\"loc_stanox\":\"52049\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"1\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"52074\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704688000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708180000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708180000\",\"timetable_variation\":\"2\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_sour
    ce\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"30\",\"train_terminated\":\"false\",\"train_id\":\"879D27MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"22215003\",\"toc_id\":\"30\",\"loc_stanox\":\"52080\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"52078\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704688000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476708060000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708060000\",\"timetable_variation\":\"2\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708180000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 1\",\"division_code\":\"23\",\"train_terminated\":\"false\",\"train_id\":\"172D53MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"11821020\",\"toc_id\":\"23\",\"loc_stanox\":\"17038\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"4\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"17052\",\"line_ind\":\"M\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704688000\",\"source_system_id\":\"
    TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708240000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708210000\",\"timetable_variation\":\"3\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"17033\",\"actual_timestamp\":\"1476708360000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 4\",\"division_code\":\"23\",\"train_terminated\":\"false\",\"train_id\":\"172D53MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"11821020\",\"toc_id\":\"23\",\"loc_stanox\":\"17033\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"17021\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476706860000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476706860000\",\"timetable_variation\":\"24\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"87245\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 2\",\"division_code\":\"88\",\"train_terminated\":\"false\",\"train_id\":\"871W26MI17\",\"offroute_ind\":\"false\",\"variation_s
    tatus\":\"LATE\",\"train_service_code\":\"22721000\",\"toc_id\":\"88\",\"loc_stanox\":\"87245\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"87244\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476708060000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708120000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"2\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708060000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"30\",\"train_terminated\":\"false\",\"train_id\":\"522N51MJ17\",\"offroute_ind\":\"false\",\"variation_status\":\"EARLY\",\"train_service_code\":\"22214000\",\"toc_id\":\"30\",\"loc_stanox\":\"72252\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"2\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"72253\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"VDDC\",\"user_id\":\"#QDP4251\",\"original_data_source\":\"SDR\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708240000\",\"timetable_variation\":\"0\",\"origin
    al_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"5\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708240000\",\"correction_ind\":\"false\",\"event_source\":\"MANUAL\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"71\",\"train_terminated\":\"false\",\"train_id\":\"801W56MB17\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"25432000\",\"toc_id\":\"71\",\"loc_stanox\":\"64237\",\"auto_expected\":\"\",\"direction_ind\":\"\",\"route\":\"\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"64231\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708360000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708360000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"51013\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 2\",\"division_code\":\"79\",\"train_terminated\":\"false\",\"train_id\":\"522D28MJ17\",\"offroute_ind\":\"false\",\"variation_status\":\"EARLY\",\"train_service_code\":\"24936004\",\"toc_id\":\"79\",\"loc_stanox\":\"51013\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"nex
    t_report_stanox\":\"51011\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476708240000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708240000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"87601\",\"actual_timestamp\":\"1476708240000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"10\",\"division_code\":\"88\",\"train_terminated\":\"false\",\"train_id\":\"872F21ML17\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"24783000\",\"toc_id\":\"88\",\"loc_stanox\":\"87601\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"1\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"87590\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708240000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708240000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708300000\",\"co
    rrection_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 2\",\"division_code\":\"80\",\"train_terminated\":\"false\",\"train_id\":\"882E71MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"24659005\",\"toc_id\":\"80\",\"loc_stanox\":\"88437\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"88515\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708300000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708300000\",\"timetable_variation\":\"0\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"88317\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 1\",\"division_code\":\"80\",\"train_terminated\":\"false\",\"train_id\":\"882K50ML17\",\"offroute_ind\":\"false\",\"variation_status\":\"ON TIME\",\"train_service_code\":\"24653005\",\"toc_id\":\"80\",\"loc_stanox\":\"88317\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"88313\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"147
    6704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476707640000\",\"timetable_variation\":\"10\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"4\",\"reporting_stanox\":\"88486\",\"actual_timestamp\":\"1476708240000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 1\",\"division_code\":\"80\",\"train_terminated\":\"false\",\"train_id\":\"895Y121K17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"24602004\",\"toc_id\":\"80\",\"loc_stanox\":\"88486\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"2\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"88485\",\"line_ind\":\"F\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708120000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708090000\",\"timetable_variation\":\"4\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"60\",\"train_terminated\":\"false\",\"train_id\":\"072L01MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"LAT
    E\",\"train_service_code\":\"23563015\",\"toc_id\":\"60\",\"loc_stanox\":\"07275\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"06362\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708270000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"60\",\"train_terminated\":\"false\",\"train_id\":\"042H23MI17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"13560015\",\"toc_id\":\"60\",\"loc_stanox\":\"06347\",\"auto_expected\":\"true\",\"direction_ind\":\"\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"06345\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704689000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708060000\",\"timetable_variation\":\"2\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"fals
    e\",\"next_report_run_time\":\"4\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708180000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"20\",\"train_terminated\":\"false\",\"train_id\":\"121F66MG17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"21731000\",\"toc_id\":\"20\",\"loc_stanox\":\"31739\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"2\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"31747\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704690000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708300000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708270000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":\"03T\",\"platform\":\" 2\",\"division_code\":\"60\",\"train_terminated\":\"false\",\"train_id\":\"042K71MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"23587103\",\"toc_id\":\"60\",\"loc_stanox\":\"03291\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"ne
    xt_report_stanox\":\"03283\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704690000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708360000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708360000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"2\",\"reporting_stanox\":\"09312\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"20\",\"train_terminated\":\"false\",\"train_id\":\"071M96MI17\",\"offroute_ind\":\"false\",\"variation_status\":\"EARLY\",\"train_service_code\":\"21730001\",\"toc_id\":\"20\",\"loc_stanox\":\"09312\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"09330\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704690000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476708180000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708210000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"2\",\"reporting_stanox\":\"32534\",\"actual_timestamp\":\"1476708240000\",\"correction
    _ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 3\",\"division_code\":\"23\",\"train_terminated\":\"false\",\"train_id\":\"432H19MJ17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"12231820\",\"toc_id\":\"23\",\"loc_stanox\":\"32534\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"2\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"32525\",\"line_ind\":\"F\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"SKHG\",\"user_id\":\"#QGM0637\",\"original_data_source\":\"SDR\",\"msg_queue_timestamp\":\"1476704690000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476695700000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476695700000\",\"timetable_variation\":\"29\",\"original_loc_timestamp\":\"\",\"current_train_id\":null,\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"\",\"reporting_stanox\":\"27263\",\"actual_timestamp\":\"1476697440000\",\"correction_ind\":\"false\",\"event_source\":\"MANUAL\",\"train_file_address\":\"PEL\",\"platform\":\"\",\"division_code\":\"00\",\"train_terminated\":\"true\",\"train_id\":\"56022FCD17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"53790125\",\"toc_id\":\"00\",\"loc_stanox\":\"27263\",\"auto_expected\":\"true\",\"direction_ind\":\"\",\"route\":\"\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704691000\",\"source_system_id\":\"TRUST
    \"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476708180000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708180000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"3\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708240000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"64\",\"train_terminated\":\"false\",\"train_id\":\"382W25ML17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"12305012\",\"toc_id\":\"64\",\"loc_stanox\":\"38006\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"1\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"38008\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704691000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"DEPARTURE\",\"gbtt_timestamp\":\"1476708240000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708240000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"false\",\"next_report_run_time\":\"6\",\"reporting_stanox\":\"00000\",\"actual_timestamp\":\"1476708180000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"M\",\"division_code\":\"23\",\"train_terminated\":\"false\",\"train_id\":\"551Y28MK17\",\"offroute_ind\":\"false\",\"variation_status\":\"EARLY\",\"train_service_code\"
    :\"21865000\",\"toc_id\":\"23\",\"loc_stanox\":\"56127\",\"auto_expected\":\"true\",\"direction_ind\":\"DOWN\",\"route\":\"2\",\"planned_event_type\":\"DEPARTURE\",\"next_report_stanox\":\"56101\",\"line_ind\":\"E\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704691000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"1476708420000\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708240000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"\",\"reporting_stanox\":\"32541\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\" 1\",\"division_code\":\"23\",\"train_terminated\":\"true\",\"train_id\":\"302H02MH17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"12355820\",\"toc_id\":\"23\",\"loc_stanox\":\"32541\",\"auto_expected\":\"true\",\"direction_ind\":\"UP\",\"route\":\"0\",\"planned_event_type\":\"DESTINATION\",\"next_report_stanox\":\"\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704691000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708120000\",\"timetable_variatio
    n\":\"3\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"32563\",\"actual_timestamp\":\"1476708300000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"71\",\"train_terminated\":\"false\",\"train_id\":\"321V42ML17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"25434000\",\"toc_id\":\"71\",\"loc_stanox\":\"32563\",\"auto_expected\":\"true\",\"direction_ind\":\"\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_report_stanox\":\"32568\",\"line_ind\":\"\"}},{\"header\":{\"msg_type\":\"0003\",\"source_dev_id\":\"\",\"user_id\":\"\",\"original_data_source\":\"SMART\",\"msg_queue_timestamp\":\"1476704691000\",\"source_system_id\":\"TRUST\"},\"body\":{\"event_type\":\"ARRIVAL\",\"gbtt_timestamp\":\"\",\"original_loc_stanox\":\"\",\"planned_timestamp\":\"1476708330000\",\"timetable_variation\":\"1\",\"original_loc_timestamp\":\"\",\"current_train_id\":\"\",\"delay_monitoring_point\":\"true\",\"next_report_run_time\":\"1\",\"reporting_stanox\":\"73822\",\"actual_timestamp\":\"1476708360000\",\"correction_ind\":\"false\",\"event_source\":\"AUTOMATIC\",\"train_file_address\":null,\"platform\":\"\",\"division_code\":\"25\",\"train_terminated\":\"false\",\"train_id\":\"791L51ME17\",\"offroute_ind\":\"false\",\"variation_status\":\"LATE\",\"train_service_code\":\"25375002\",\"toc_id\":\"25\",\"loc_stanox\":\"73822\",\"auto_expected\":\"true\",\"direction_ind\":\"\",\"route\":\"0\",\"planned_event_type\":\"ARRIVAL\",\"next_re
    port_stanox\":\"73799\",\"line_ind\":\"\"}}]
    """ <> <<0>> <> "\n"
  end

end
